name: Better_Villager_Trade
version: '${version}'
main: com.example.customvillagertrades.CustomVillagerTrades
api-version: '1.16'
commands:
  bvt:
    description: plugin help
    usage: /<command>
    permission: bvt.admin